In [102]:
#Importing libraries
import numpy as np

In [103]:
import pandas as pd

In [104]:
!pip install apyori

Requirement already satisfied: apyori in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (1.1.2)

In [105]:
#loading dataset 

df = pd.read_csv("Market_Basket_Optimisation.csv" , names=[i for i in range(0,20)])

In [106]:
#The dataset shows the market basket of different customers while they bought items. Based on these combinations only 
#we will work out further

df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [107]:
#Replacing all null values with 0 to simplify our task
df.fillna(0,inplace=True)

In [108]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,chutney,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,turkey,avocado,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,mineral water,milk,energy bar,whole wheat rice,green tea,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7498,chicken,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7499,escalope,green tea,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [109]:

#making a list where i will include all purchaces in each index of the list
purchases = []

#adding items of each purchase in the list as each index as a unique purchase
for i in range (0,len(df)):
    purchases.append([str(df.values[i,j]) for j in range(0,20) if str(df.values[i,j]) != '0'])

In [110]:
#Viewing items purchased at 2nd number
purchases[1]

['burgers', 'meatballs', 'eggs']

In [111]:
purchases[34]

['cookies']

In [112]:
#now importing and applying model 
from apyori import apriori

#Setting the hyperparameters 
model_0_5 = apriori(purchases, min_support=0.005, min_confidance=0.2, min_lift=3, min_length=2)

#min support of 0.5% with confidence 20 % and min length 2

model_0_2 = apriori(purchases, min_support=0.002, min_confidance=0.2, min_lift=3, min_length=2)
#finalising min support of 0.2% with confidence 20 % and min length 2 
#(Since it is found to be best on the basis of optimum number of association samples)

In [113]:
model_0_5

In [114]:
Result_0_5 = list(model_0_5)

In [115]:
Result_0_5

[RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'escalope'}), items_add=frozenset({'mushroom cream sauce'}), confidence=0.0722689075630252, lift=3.7908326967150496), OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]),
 RelationRecord(items=frozenset({'pasta', 'escalope'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'escalope'}), items_add=frozenset({'pasta'}), confidence=0.07394957983193277, lift=4.700811850163794), OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'herb & pepper'}), confidence=0.1628222523744912, lift=3.291993841134928), OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2919938411349285)]),
 RelationRecord(items=frozenset({'tomato sauce', 'ground beef'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'tomato sauce'}), confidence=0.054274084124830396, lift=3.840659481324083), OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3773584905660377, lift=3.840659481324083)]),
 RelationRecord(items=frozenset({'olive oil', 'whole wheat pasta'}), support=0.007998933475536596, ordered_statistics=[OrderedStatistic(items_base=frozenset({'olive oil'}), items_add=frozenset({'whole wheat pasta'}), confidence=0.12145748987854252, lift=4.1224100976422955), OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.122410097642296)]),
 RelationRecord(items=frozenset({'pasta', 'shrimp'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050847, lift=4.506672147735896), OrderedStatistic(items_base=frozenset({'shrimp'}), items_add=frozenset({'pasta'}), confidence=0.0708955223880597, lift=4.506672147735896)]),
 RelationRecord(items=frozenset({'chocolate', 'frozen vegetables', 'shrimp'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables'}), items_add=frozenset({'chocolate', 'shrimp'}), confidence=0.055944055944055944, lift=3.1084175084175087), OrderedStatistic(items_base=frozenset({'shrimp'}), items_add=frozenset({'chocolate', 'frozen vegetables'}), confidence=0.07462686567164178, lift=3.2545123221103784), OrderedStatistic(items_base=frozenset({'chocolate', 'frozen vegetables'}), items_add=frozenset({'shrimp'}), confidence=0.23255813953488375, lift=3.2545123221103784), OrderedStatistic(items_base=frozenset({'chocolate', 'shrimp'}), items_add=frozenset({'frozen vegetables'}), confidence=0.29629629629629634, lift=3.1084175084175087)]),
 RelationRecord(items=frozenset({'ground beef', 'frozen vegetables', 'spaghetti'}), support=0.008665511265164644, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'spaghetti', 'frozen vegetables'}), confidence=0.08819538670284939, lift=3.165328208890303), OrderedStatistic(items_base=frozenset({'spaghetti', 'frozen vegetables'}), items_add=frozenset({'ground beef'}), confidence=0.31100478468899523, lift=3.165328208890303)]),
 RelationRecord(items=frozenset({'mineral water', 'frozen vegetables', 'shrimp'}), support=0.007199040127982935, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables'}), items_add=frozenset({'mineral water', 'shrimp'}), confidence=0.07552447552447553, lift=3.2006163328197226), OrderedStatistic(items_base=frozenset({'mineral water', 'shrimp'}), items_add=frozenset({'frozen vegetables'}), confidence=0.30508474576271183, lift=3.200616332819722)]),
 RelationRecord(items=frozenset({'olive oil', 'frozen vegetables', 'spaghetti'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'olive oil'}), items_add=frozenset({'spaghetti', 'frozen vegetables'}), confidence=0.08704453441295547, lift=3.124024175270713), OrderedStatistic(items_base=frozenset({'spaghetti', 'frozen vegetables'}), items_add=frozenset({'olive oil'}), confidence=0.20574162679425836, lift=3.1240241752707125)]),
 RelationRecord(items=frozenset({'spaghetti', 'frozen vegetables', 'shrimp'}), support=0.005999200106652446, ordered_statistics=[OrderedStatistic(items_base=frozenset({'shrimp'}), items_add=frozenset({'spaghetti', 'frozen vegetables'}), confidence=0.08395522388059701, lift=3.013148968078269), OrderedStatistic(items_base=frozenset({'spaghetti', 'frozen vegetables'}), items_add=frozenset({'shrimp'}), confidence=0.21531100478468898, lift=3.0131489680782684)]),
 RelationRecord(items=frozenset({'spaghetti', 'frozen vegetables', 'tomatoes'}), support=0.006665777896280496, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables'}), items_add=frozenset({'spaghetti', 'tomatoes'}), confidence=0.06993006993006994, lift=3.341053850607991), OrderedStatistic(items_base=frozenset({'tomatoes'}), items_add=frozenset({'spaghetti', 'frozen vegetables'}), confidence=0.09746588693957116, lift=3.4980460188216425), OrderedStatistic(items_base=frozenset({'spaghetti', 'frozen vegetables'}), items_add=frozenset({'tomatoes'}), confidence=0.23923444976076558, lift=3.4980460188216425), OrderedStatistic(items_base=frozenset({'spaghetti', 'tomatoes'}), items_add=frozenset({'frozen vegetables'}), confidence=0.3184713375796179, lift=3.341053850607991)]),
 RelationRecord(items=frozenset({'grated cheese', 'ground beef', 'spaghetti'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'grated cheese', 'spaghetti'}), confidence=0.054274084124830396, lift=3.283144395325426), OrderedStatistic(items_base=frozenset({'grated cheese', 'spaghetti'}), items_add=frozenset({'ground beef'}), confidence=0.3225806451612903, lift=3.283144395325426)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef', 'mineral water'}), support=0.006665777896280496, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'herb & pepper', 'mineral water'}), confidence=0.067842605156038, lift=3.9756826662143836), OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef', 'mineral water'}), confidence=0.1347708894878706, lift=3.292887433382793), OrderedStatistic(items_base=frozenset({'ground beef', 'mineral water'}), items_add=frozenset({'herb & pepper'}), confidence=0.16286644951140067, lift=3.2928874333827935), OrderedStatistic(items_base=frozenset({'herb & pepper', 'mineral water'}), items_add=frozenset({'ground beef'}), confidence=0.39062500000000006, lift=3.975682666214383)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef', 'spaghetti'}), support=0.006399146780429276, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'herb & pepper', 'spaghetti'}), confidence=0.06512890094979648, lift=4.004359721511667), OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef', 'spaghetti'}), confidence=0.1293800539083558, lift=3.3009516475053635), OrderedStatistic(items_base=frozenset({'ground beef', 'spaghetti'}), items_add=frozenset({'herb & pepper'}), confidence=0.163265306122449, lift=3.3009516475053635), OrderedStatistic(items_base=frozenset({'herb & pepper', 'spaghetti'}), items_add=frozenset({'ground beef'}), confidence=0.3934426229508197, lift=4.004359721511667)]),
 RelationRecord(items=frozenset({'ground beef', 'shrimp', 'spaghetti'}), support=0.005999200106652446, ordered_statistics=[OrderedStatistic(items_base=frozenset({'spaghetti'}), items_add=frozenset({'ground beef', 'shrimp'}), confidence=0.03445635528330781, lift=3.0053153602336264), OrderedStatistic(items_base=frozenset({'ground beef', 'shrimp'}), items_add=frozenset({'spaghetti'}), confidence=0.5232558139534884, lift=3.005315360233627)]),
 RelationRecord(items=frozenset({'soup', 'mineral water', 'milk'}), support=0.008532195707239034, ordered_statistics=[OrderedStatistic(items_base=frozenset({'soup'}), items_add=frozenset({'milk', 'mineral water'}), confidence=0.16886543535620052, lift=3.518498973907945), OrderedStatistic(items_base=frozenset({'mineral water', 'milk'}), items_add=frozenset({'soup'}), confidence=0.17777777777777776, lift=3.5184989739079446)]),
 RelationRecord(items=frozenset({'olive oil', 'milk', 'spaghetti'}), support=0.007199040127982935, ordered_statistics=[OrderedStatistic(items_base=frozenset({'olive oil'}), items_add=frozenset({'spaghetti', 'milk'}), confidence=0.10931174089068825, lift=3.0825089038385434), OrderedStatistic(items_base=frozenset({'spaghetti', 'milk'}), items_add=frozenset({'olive oil'}), confidence=0.20300751879699247, lift=3.0825089038385434)]),
 RelationRecord(items=frozenset({'soup', 'olive oil', 'mineral water'}), support=0.005199306759098787, ordered_statistics=[OrderedStatistic(items_base=frozenset({'olive oil'}), items_add=frozenset({'soup', 'mineral water'}), confidence=0.07894736842105264, lift=3.423030118649225), OrderedStatistic(items_base=frozenset({'soup'}), items_add=frozenset({'olive oil', 'mineral water'}), confidence=0.1029023746701847, lift=3.7288440212611373), OrderedStatistic(items_base=frozenset({'olive oil', 'mineral water'}), items_add=frozenset({'soup'}), confidence=0.18840579710144928, lift=3.7288440212611373), OrderedStatistic(items_base=frozenset({'soup', 'mineral water'}), items_add=frozenset({'olive oil'}), confidence=0.22543352601156072, lift=3.4230301186492245)]),
 RelationRecord(items=frozenset({'pancakes', 'olive oil', 'spaghetti'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'olive oil'}), items_add=frozenset({'pancakes', 'spaghetti'}), confidence=0.07692307692307693, lift=3.052910052910053), OrderedStatistic(items_base=frozenset({'pancakes', 'spaghetti'}), items_add=frozenset({'olive oil'}), confidence=0.20105820105820105, lift=3.0529100529100526)])]

In [116]:
df_result_0_5 = pd.DataFrame(Result_0_5)

In [117]:
#Showing the sample results based on min support 0.5%
df_result_0_5

,items,support,ordered_statistics
0,"(mushroom cream sauce, escalope)",0.005733,"[((escalope), (mushroom cream sauce), 0.072268..."
1,"(pasta, escalope)",0.005866,"[((escalope), (pasta), 0.07394957983193277, 4...."
2,"(herb & pepper, ground beef)",0.015998,"[((ground beef), (herb & pepper), 0.1628222523..."
3,"(tomato sauce, ground beef)",0.005333,"[((ground beef), (tomato sauce), 0.05427408412..."
4,"(olive oil, whole wheat pasta)",0.007999,"[((olive oil), (whole wheat pasta), 0.12145748..."
5,"(pasta, shrimp)",0.005066,"[((pasta), (shrimp), 0.3220338983050847, 4.506..."
6,"(chocolate, frozen vegetables, shrimp)",0.005333,"[((frozen vegetables), (chocolate, shrimp), 0...."
7,"(ground beef, frozen vegetables, spaghetti)",0.008666,"[((ground beef), (spaghetti, frozen vegetables..."
8,"(mineral water, frozen vegetables, shrimp)",0.007199,"[((frozen vegetables), (mineral water, shrimp)..."
9,"(olive oil, frozen vegetables, spaghetti)",0.005733,"[((olive oil), (spaghetti, frozen vegetables),..."
10,"(spaghetti, frozen vegetables, shrimp)",0.005999,"[((shrimp), (spaghetti, frozen vegetables), 0...."
11,"(spaghetti, frozen vegetables, tomatoes)",0.006666,"[((frozen vegetables), (spaghetti, tomatoes), ..."
12,"(grated cheese, ground beef, spaghetti)",0.005333,"[((ground beef), (grated cheese, spaghetti), 0..."
13,"(herb & pepper, ground beef, mineral water)",0.006666,"[((ground beef), (herb & pepper, mineral water..."
14,"(herb & pepper, ground beef, spaghetti)",0.006399,"[((ground beef), (herb & pepper, spaghetti), 0..."
15,"(ground beef, shrimp, spaghetti)",0.005999,"[((spaghetti), (ground beef, shrimp), 0.034456..."
16,"(soup, mineral water, milk)",0.008532,"[((soup), (milk, mineral water), 0.16886543535..."
17,"(olive oil, milk, spaghetti)",0.007199,"[((olive oil), (spaghetti, milk), 0.1093117408..."
18,"(soup, olive oil, mineral water)",0.005199,"[((olive oil), (soup, mineral water), 0.078947..."
19,"(pancakes, olive oil, spaghetti)",0.005066,"[((olive oil), (pancakes, spaghetti), 0.076923..."

In [118]:
#Final result with o.2% min support
Result = list(model_0_2)

In [119]:
df_final = pd.DataFrame(Result)

In [120]:
df_final

,items,support,ordered_statistics
0,"(barbecue sauce, turkey)",0.002533,"[((barbecue sauce), (turkey), 0.23456790123456..."
1,"(brownies, cottage cheese)",0.003466,"[((brownies), (cottage cheese), 0.102766798418..."
2,"(extra dark chocolate, chicken)",0.002800,"[((chicken), (extra dark chocolate), 0.0466666..."
3,"(light cream, chicken)",0.004533,"[((chicken), (light cream), 0.0755555555555555..."
4,"(cooking oil, light cream)",0.002800,"[((cooking oil), (light cream), 0.054830287206..."
...,...,...,...
273,"(mineral water, spaghetti, milk, turkey)",0.002666,"[((milk), (spaghetti, mineral water, turkey), ..."
274,"(pancakes, olive oil, mineral water, spaghetti)",0.002800,"[((olive oil), (pancakes, spaghetti, mineral w..."
275,"(olive oil, mineral water, spaghetti, shrimp)",0.002266,"[((olive oil), (spaghetti, mineral water, shri..."
276,"(olive oil, mineral water, spaghetti, tomatoes)",0.002266,"[((olive oil), (spaghetti, mineral water, toma..."
277,"(soup, pancakes, spaghetti, mineral water)",0.002266,"[((mineral water), (soup, pancakes, spaghetti)..."

In [121]:
support = df_final.support

In [122]:
#seperating the elements of ordered stats in correct order
lhs = []
rhs = []
Confidence = []
Lift = []

for i in range(len(df_final)):
    single_list = df_final['ordered_statistics'][i][0]
    lhs.append(list(single_list[0]))
    rhs.append(list(single_list[1]))
    Confidence.append(single_list[2])
    Lift.append(single_list[3])

In [123]:
#Presenting then as a new Data Frame
df_final_result = pd.DataFrame(lhs)

In [124]:
df_final_result["rhs"] = rhs

In [125]:
df_final_result["Support"] = support

In [126]:
df_final_result["Confidence"] = Confidence

In [127]:
df_final_result["Lift"] = Lift

In [128]:
df_final_result

,0,1,rhs,Support,Confidence,Lift
0,barbecue sauce,None,[turkey],0.002533,0.234568,3.751586
1,brownies,None,[cottage cheese],0.003466,0.102767,3.225330
2,chicken,None,[extra dark chocolate],0.002800,0.046667,3.889407
3,chicken,None,[light cream],0.004533,0.075556,4.843951
4,cooking oil,None,[light cream],0.002800,0.054830,3.515231
...,...,...,...,...,...,...
273,milk,None,"[spaghetti, mineral water, turkey]",0.002666,0.020576,3.215449
274,olive oil,None,"[pancakes, spaghetti, mineral water]",0.002800,0.042510,3.707772
275,olive oil,None,"[spaghetti, mineral water, shrimp]",0.002266,0.034413,4.033306
276,olive oil,None,"[spaghetti, mineral water, tomatoes]",0.002266,0.034413,3.687594
277,mineral water,None,"[soup, pancakes, spaghetti]",0.002266,0.009508,3.241738

In [129]:
#Rearranging the columns
df_final_result.columns = ['lhs',1,'rhs','Support','Confidence','Lift']

In [130]:
df_final_result

,lhs,1,rhs,Support,Confidence,Lift
0,barbecue sauce,None,[turkey],0.002533,0.234568,3.751586
1,brownies,None,[cottage cheese],0.003466,0.102767,3.225330
2,chicken,None,[extra dark chocolate],0.002800,0.046667,3.889407
3,chicken,None,[light cream],0.004533,0.075556,4.843951
4,cooking oil,None,[light cream],0.002800,0.054830,3.515231
...,...,...,...,...,...,...
273,milk,None,"[spaghetti, mineral water, turkey]",0.002666,0.020576,3.215449
274,olive oil,None,"[pancakes, spaghetti, mineral water]",0.002800,0.042510,3.707772
275,olive oil,None,"[spaghetti, mineral water, shrimp]",0.002266,0.034413,4.033306
276,olive oil,None,"[spaghetti, mineral water, tomatoes]",0.002266,0.034413,3.687594
277,mineral water,None,"[soup, pancakes, spaghetti]",0.002266,0.009508,3.241738

In [131]:
#Dropping the meaningless column
df_final_result.drop(columns=[1],inplace=True)

In [132]:
df_final_result

,lhs,rhs,Support,Confidence,Lift
0,barbecue sauce,[turkey],0.002533,0.234568,3.751586
1,brownies,[cottage cheese],0.003466,0.102767,3.225330
2,chicken,[extra dark chocolate],0.002800,0.046667,3.889407
3,chicken,[light cream],0.004533,0.075556,4.843951
4,cooking oil,[light cream],0.002800,0.054830,3.515231
...,...,...,...,...,...
273,milk,"[spaghetti, mineral water, turkey]",0.002666,0.020576,3.215449
274,olive oil,"[pancakes, spaghetti, mineral water]",0.002800,0.042510,3.707772
275,olive oil,"[spaghetti, mineral water, shrimp]",0.002266,0.034413,4.033306
276,olive oil,"[spaghetti, mineral water, tomatoes]",0.002266,0.034413,3.687594
277,mineral water,"[soup, pancakes, spaghetti]",0.002266,0.009508,3.241738

In [133]:
#Sorting the value as per the Lift value for each assiciations
df_final_result.sort_values('Lift', ascending=False).head(10)

,lhs,rhs,Support,Confidence,Lift
86,escalope,"[mushroom cream sauce, pasta]",0.002533,0.031933,11.976387
20,mushroom cream sauce,[pasta],0.002666,0.139860,8.890601
10,fresh tuna,[fromage blanc],0.002400,0.107784,7.926383
110,frozen vegetables,"[parmesan cheese, tomatoes]",0.002133,0.022378,6.993939
156,olive oil,"[mineral water, whole wheat pasta]",0.003866,0.058704,6.115863
203,ground beef,"[herb & pepper, chocolate, mineral water]",0.002266,0.023066,5.767390
44,ground beef,"[herb & pepper, burgers]",0.002266,0.023066,5.581345
64,chicken,"[light cream, mineral water]",0.002400,0.040000,5.455273
12,fromage blanc,[honey],0.003333,0.245098,5.164271
252,frozen vegetables,"[olive oil, spaghetti, tomatoes]",0.002133,0.022378,5.086501

In [134]:
#Final Association result of the dataset along with its minimum supprot , Confidence and Lift
df_final_result.sort_values('Lift', ascending=False).head(10)

,lhs,rhs,Support,Confidence,Lift
86,escalope,"[mushroom cream sauce, pasta]",0.002533,0.031933,11.976387
20,mushroom cream sauce,[pasta],0.002666,0.139860,8.890601
10,fresh tuna,[fromage blanc],0.002400,0.107784,7.926383
110,frozen vegetables,"[parmesan cheese, tomatoes]",0.002133,0.022378,6.993939
156,olive oil,"[mineral water, whole wheat pasta]",0.003866,0.058704,6.115863
203,ground beef,"[herb & pepper, chocolate, mineral water]",0.002266,0.023066,5.767390
44,ground beef,"[herb & pepper, burgers]",0.002266,0.023066,5.581345
64,chicken,"[light cream, mineral water]",0.002400,0.040000,5.455273
12,fromage blanc,[honey],0.003333,0.245098,5.164271
252,frozen vegetables,"[olive oil, spaghetti, tomatoes]",0.002133,0.022378,5.086501